apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Deficiency_Pop
  description: |
    Defpop is an application to manage the deficiencies by the physicians.
  links:
    - title: Website
      url: https://dp-reg-webser1.hylandqa.net/DeficiencyPop/Login.aspx
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: HylandExperience/Hyland-Developers-Portal
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
    datadoghq.com/dashboard-url: https://hxp.datadoghq.com/apm/home
    jira.com/project-key: FCCSEU
    jira.com/components: 'Content Repo Module Package Squad'
spec:
  type: website
  owner: CRMP_SQUAD
  lifecycle: experimental
